### ISSUE TITLE
Possibly missing some files 

### ISSUE THREAD

**Issue by risunz** [nishlumi/transform_ctrl_gizmo#1]
I tried to load the plugin using Godot 4.1.2 Stable and getting these errors:
  

- res://addons/transform_ctrl_gizmo-main/server.gd:5 - Parse Error: Preload file "res://addons/transform_ctrl_gizmo/gizmo_template2.tscn" does not exist.
- res://addons/transform_ctrl_gizmo-main/server.gd:5 - Parse Error: Could not resolve type for variable "gizmo_template".

Upon reading more lines of the error, my guess is the project is missing "res://new_standard_material_3d.tres" file that is needed for gizmo_template2.tscn and gizmo_template1.tscn

**Comment by nishlumi** [comment]
Thank you for trying it.
Sorry about the missing files.
I will check it properly and try to upload again.

**Comment by nishlumi** [comment]
I fixed the bugs and change the repository as sample game project with this addon.
Please try it.

**Comment by risunz** [comment]
It works! I will check it out and see if there is anything I could contribute.
